"""
automaton definition for PeriConto
"""
UI_state = {
        "start"                           : {
                "show"  : ["ontology_control",
                           "ontology_load",
                           "ontology_create"],
                "hide"  : ["ontology_save",
                           "ontology_save_as",
                           "tab_lists_control",
                           "primitives_control",
                           ],
                "action": [],
                },
        "create ontology"                 : {
                "show"  : ["ontology_save",
                           "ontology_save_as",
                           "tab_lists_control",
                           "brick_control",
                           "brick_create"],
                "hide"  : ["ontology_load",
                           "ontology_create",
                           "brick_delete",
                           "brick_add_item",
                           "brick_remove_item",
                           "brick_add_primitive",
                           "brick_rename",
                           "tree_control",
                           "Tree",
                           "tree_select_brick",
                           ],
                "action": ["createOntology",
                           "markChanged",
                           "putBrickList"],
                },
        "load ontology"                   : {
                "show"  : ["ontology_save",
                           "ontology_save_as",
                           "tab_lists_control",
                           "brick_control",
                           "brick_create",
                           "tree_control",
                           "Tree",
                           "tree_select_brick"
                           ],
                "hide"  : ["ontology_create",
                           "ontology_load",
                           "brick_delete",
                           "brick_add_item",
                           "brick_remove_item",
                           "brick_add_primitive",
                           "brick_rename",
                           ],
                "action": ["loadOntology",
                           "putBrickList",
                           ],
                },
        "new brick"                       : {
                "show"  : ["ontology_save",
                           "ontology_save_as",
                           "tab_lists_control",
                           "brick_control",
                           "brick_create",
                           "tree_control",
                           "Tree",
                           "tree_select_brick"
                           ],
                "hide"  : ["ontology_create",
                           "ontology_load",
                           "brick_delete",
                           "brick_add_item",
                           "brick_remove_item",
                           "brick_add_primitive",
                           "brick_rename",
                           ],
                "action": ["newBrick",
                           "getBrickDataTuples",
                           "putBrickList",
                           "markChanged",
                           ],
                },
        "selected brick"                  : {
                "show"  : ["ontology_save",
                           "ontology_save_as",
                           "tab_lists_control",
                           "brick_control",
                           "brick_create",
                           "brick_delete",
                           "brick_rename",
                           "tree_control",
                           "Tree",
                           "tree_select_brick"
                           ],
                "hide"  : ["ontology_create",
                           "ontology_load",
                           "brick_add_item",
                           "brick_remove_item",
                           "brick_add_primitive",
                           ],
                "action": ["getBrickDataTuples",
                           "putBrickDataTuples",
                           ],
                },
        "brick root in brick tree selected"     : {
                "show"  : ["ontology_save",
                           "ontology_save_as",
                           "tab_lists_control",
                           "brick_control",
                           "brick_create",
                           "brick_delete",
                           "brick_rename",
                           "tree_control",
                           "brick_add_item",
                           "brick_add_primitive",
                           "Tree",
                           "tree_select_brick"
                           ],
                "hide"  : ["ontology_create",
                           "ontology_load",
                           "brick_remove_item",
                           ],
                "action": ["selectedItemInBrickTree"],
                },
        "item in brick tree selected"     : {
                "show"  : ["ontology_save",
                           "ontology_save_as",
                           "tab_lists_control",
                           "brick_control",
                           "brick_create",
                           "brick_delete",
                           "brick_rename",
                           "tree_control",
                           "brick_add_item",
                           "brick_remove_item",
                           "brick_add_primitive",
                           "Tree",
                           "tree_select_brick"
                           ],
                "hide"  : ["ontology_create",
                           "ontology_load",
                           ],
                "action": ["selectedItemInBrickTree"],
                },
        "value in brick tree selected"    : {
                "show"  : ["ontology_save",
                           "ontology_save_as",
                           "tab_lists_control",
                           "brick_control",
                           "brick_create",
                           "brick_delete",
                           "brick_rename",
                           "brick_remove_item",
                           ],
                "hide"  : ["ontology_create",
                           "ontology_load",
                           "tree_control",
                           "brick_add_item",
                           "brick_add_primitive",
                           "Tree",
                           "tree_select_brick",
                           ],
                "action": [],
                },
        "primitive in brick tree selected": {
                "show"  : ["ontology_save",
                           "ontology_save_as",
                           "tab_lists_control",
                           "brick_control",
                           "brick_create",
                           "brick_delete",
                           "brick_rename",
                           ],
                "hide"  : ["ontology_create",
                           "ontology_load",
                           "tree_control",
                           "brick_add_item",
                           "brick_remove_item",
                           "brick_add_primitive",
                           "Tree",
                           "tree_select_brick",
                           ],
                "action": [],
                },
        "remove item from brick tree"     : {
                "show"  : [],
                "hide"  : [],
                "action": ["removeItemFromBrickTree",
                           "markChanged",
                           "getBrickDataTuples",
                           "putBrickDataTuples",
                           ],
                },
        "asks for adding an item"         : {
                "show"  : ["ontology_save",
                           "ontology_save_as",
                           "tab_lists_control",
                           "brick_control",
                           "brick_create",
                           "tree_control",
                           "Tree",
                           "tree_select_brick"
                           ],
                "hide"  : ["ontology_create",
                           "ontology_load",
                           "brick_delete",
                           "brick_add_item",
                           "brick_remove_item",
                           "brick_add_primitive",
                           "brick_rename",
                           ],
                "action": ["getExistingItemNames",
                           "markChanged", ],
                },
        "ask for adding a primitive"      : {
                "show"  : ["ontology_save",
                           "ontology_save_as",
                           "tab_lists_control",
                           "brick_control",
                           "brick_delete",
                           "brick_add_item",
                           "brick_remove_item",
                           "brick_add_primitive",
                           "brick_rename",
                           "brick_create",
                           ],
                "hide"  : ["ontology_create",
                           "ontology_load",
                           "primitives_line_edit",
                           "primitives_text_edit",
                           "Tree",
                           "tree_control",
                           "tree_select_brick"
                           ],
                "action": ["getExistingItemNames",
                           "markChanged", ], 
                },
        "rename brick" : {
                "show"  : ["ontology_save",
                           "ontology_save_as",
                           "tab_lists_control",
                           "brick_control",
                           "brick_delete",
                           "brick_add_item",
                           "brick_remove_item",
                           "brick_add_primitive",
                           "brick_rename",
                           "brick_create",
                           ],
                "hide"  : ["ontology_create",
                           "ontology_load",
                           "primitives_line_edit",
                           "primitives_text_edit",
                           "Tree",
                           "tree_control",
                           "tree_select_brick"
                           ],
                "action": ["renameBrick",
                           "markChanged", ], 
                 },
         "changed": {
                "show"  : ["ontology_save",],
                "hide"  : [],
                "action": [],
                },
        "do nothing"                      : {
                "show"  : [],
                "hide"  : [],
                "action": [],
                },
        "save"                      : {
                "show"  : [],
                "hide"  : ["ontology_save",],
                "action": ["saveBricks"],
                },
        }

# keys = sorted(UI_state.keys())
# print("automaton keys")
# for k in keys:
#   print(k)
# print("============================\n")
# pass
