# Form implementation generated from reading ui file 'VisualiseAutomata.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(981, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 591, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget_3)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.pushExit = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.pushExit.setObjectName("pushExit")
        self.horizontalLayout_3.addWidget(self.pushExit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushVisualise = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.pushVisualise.setObjectName("pushVisualise")
        self.horizontalLayout_3.addWidget(self.pushVisualise)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushSave = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.pushSave.setObjectName("pushSave")
        self.horizontalLayout_3.addWidget(self.pushSave)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(630, 0, 351, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushMinimise = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.pushMinimise.setObjectName("pushMinimise")
        self.horizontalLayout_2.addWidget(self.pushMinimise)
        self.pushMaximise = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.pushMaximise.setObjectName("pushMaximise")
        self.horizontalLayout_2.addWidget(self.pushMaximise)
        self.pushNormal = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.pushNormal.setObjectName("pushNormal")
        self.horizontalLayout_2.addWidget(self.pushNormal)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "brick-automaton"))
        self.comboBox.setItemText(1, _translate("MainWindow", "tree_automaton"))
        self.pushExit.setText(_translate("MainWindow", "exit"))
        self.pushVisualise.setText(_translate("MainWindow", "visualise"))
        self.pushSave.setText(_translate("MainWindow", "save"))
        self.pushMinimise.setText(_translate("MainWindow", "min"))
        self.pushMaximise.setText(_translate("MainWindow", "max"))
        self.pushNormal.setText(_translate("MainWindow", "norm"))
